name: "units-test"
on:
  pull_request:
  push:
    branches:

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  simple-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: ./
      with:
        files: example-env/simple/env.yaml
    - run: echo "${{ env.WEBSERVER_URL }}"